// =============================================================================
// Water Engine v2.0.0
// Copyright(C) 2026 Will The Water
// =============================================================================

#pragma once
#include "Core/CoreMinimal.h"
#include "Core/JsonTypes.h"
#include "GameConfigData.h"  // Generated by CMake

namespace we
{
    struct GameConfig
    {
        GameConfig();

		// Settings
		float StartupGlobalVolume;

		
		string DefaultBackground;
		
		string LevelOneBackground;
		
		string CharacterSheetIdle;
		string CharacterSheetWalk;

		string DefaultMusic;
		string DefaultAmbient;
		string DefaultButton;
		string DefaultButtonHoverSound;
		string DefaultButtonClickSound;
		string Footstep1;
		string Footstep2;
		string Footstep3;
		string Footstep4;
    };

    inline const GameConfig GC;
}