// =============================================================================
// Water Engine v2.0.0
// Copyright(C) 2026 Will The Water
// =============================================================================

#include "EngineConfig.h"
#include "EngineConfigData.h"  // Generated by CMake
#include <nlohmann/json.hpp>

namespace we
{
    EngineConfig::EngineConfig()
    {
        // Parse the embedded JSON string (generated from Config/EngineConfig.json)
        json Config = json::parse(EMBEDDED_ENGINE_CONFIG);

        WindowSize = { Config["WindowSize"][0], Config["WindowSize"][1] };
        AspectRatio = { Config["AspectRatio"][0], Config["AspectRatio"][1] };
        WindowMinimumSize = { Config["WindowMinimumSize"][0], Config["WindowMinimumSize"][1] };
        FullscreenMode = Config["FullscreenMode"];
        SetRenderSmooth = Config["SetRenderSmooth"];
        WindowName = Config["WindowName"];
        DisableSFMLLogs = Config["DisableSFMLLogs"];
        MaxDeltaTime = sf::seconds(Config["MaxDeltaTime"]);
        WindowIcon = Config["WindowIcon"];
        DefaultBackground = Config["DefaultBackground"];
    }
}